CPS-IT/typo3-project-template

- composer.json
- composer.lock
With the stable release of `cpsit/project-builder`, we can finally update the requirement in this library as well.
> [BUGFIX] Require cpsit/project-builder ^1.0

- templates/src/.gitignore.twig
With this PR, cache files of PHP-CS-Fixer are now excluded from Git in new project files.
> [BUGFIX] Exclude `.php-cs-fixer.cache` file in new projects

- templates/src/composer.json.twig
The Composer scripts `lint:editorconfig` and `fix:editorconfig` require the package `armin/editorconfig-cli` to be installed.
> [BUGFIX] Add `armin/editorconfig-cli` to `composer.json` template

- templates/src/composer.json.twig
The previously used syntax did not always find the correct paths to package files used for PHPStan analyze.
> [BUGFIX] Use correct syntax to find package paths for PHPStan analyze

- templates/src/deploy.php
The `cachetool:clear:opcache` task invocation was disabled by accident. It is now re-enabled.
> [BUGFIX] Re-enable commented opcache clear in deploy.php template

- composer.json
This PR removes some outdated plugins from the `allow-plugins` configuration. Those became obsolete with the release of Project Builder 1.0.0.
> [BUGFIX] Remove superfluous `allow-plugins` configuration

- config.yaml
This PR provides default values for the selected database version used within DDEV. The following default values are configured:
> [BUGFIX] Provide default value for DDEV database version

- templates/src/composer.json.twig
This PR addresses #13. It resets the installed TYPO3 core extension to the `TYPO3/default` package. See: https://get.typo3.org/misc/composer/helper
- `typo3/cms-lowlevel`
- `typo3/cms-opendocs`
- `typo3/cms-recordlist`
- `typo3/cms-recycler`
- `typo3/cms-redirects`
- `typo3/cms-reports`
- `typo3/cms-scheduler`
- `typo3/cms-felogin`
- `typo3/cms-sys-note`
- `typo3/cms-t3editor`
Resolves #13.
> [TASK] Use TYPO3's default preset for core extensions

- .github/dependabot.yml
The default versioning strategy should be good enough for this package. With the current setting, no updates are possible.
> [BUGFIX] Use default versioning strategy for Dependabot Composer updates

- .github/workflows/cgl.yaml
- composer.json
- composer.lock
With CPS-IT/project-builder#78, it is now possible to add the `cpsit/project-builder` as productive dependency to the `composer.json` file. This allows us to explicitly declare the supported version ranges for this template.
> [FEATURE] Explicitly require `cpsit/project-builder`

- CONTRIBUTING.md
Until now we stated a requirements in the `Contribution.md` as follows:
```markdown
- Composer
- PHP >= 8.1
```
This is both incorrect and imho unnecessary since the PHP requirement actually derives from the [Project Builder](https://github.com/CPS-IT/project-builder) which states `PHP >= 8.0`. Also, again my humble opinion, `Composer` should be a no-brainer in this context. The only requirement worth mentioning is probably `Docker` which is needed to run:
```bash
composer validate-schema
``` 
However, this requirement is disclaimed in the adjacent bash snippet.
> [DOCS] fix contribution requirements

- config.yaml
- templates/next-steps.html.twig
- templates/src/composer.json.twig
With today's sprint release of TYPO3 v12, we can now switch the available TYPO3 version for new projects from `12.2` to `12.3`.
> [TASK] Use TYPO3 v12.3 as available version for new projects

- config.yaml
- templates/src/composer.json.twig
This PR adds the possibility to select additional TYPO3 system extensions during project generation. Those will be added to the final `composer.json`.
> [FEATURE] Allow selection of additional system extensions

- README.md
- config.yaml
- templates/next-steps.html.twig
- templates/src/composer.json.twig
With the release of TYPO3 v12.4 LTS, we can now switch to the stable version for new projects.
> [FEATURE] Switch to TYPO3 v12.4 LTS

- templates/src/composer.json.twig
EXT:recordlist was merged into EXT:backend with TYPO3 12.0. See https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98443-ExtensionRecordlistMergedIntoBackend.html for reference.
> [BUGFIX] Do not require typo3/cms-recordlist for TYPO3 v12 projects

- config.yaml
- templates/src/composer.json.twig
With yesterday's TYPO3 v12 LTS release, new stable versions of TYPO3 testing framework were released as well. The new versions are now used for new projects:
- TYPO3 11.5: TYPO3 testing framework v7
- TYPO3 12.4: TYPO3 testing framework v8
> [FEATURE] Switch to stable versions of TYPO3 testing framework

- config.yaml
The `deploy.php.twig` file was referenced as resolved file (`deploy.php`) instead of its source template file (`deploy.php.twig`). This is now fixed and a `deploy.php` file will no longer be processed if the Deployer feature is disabled.
> [BUGFIX] Skip deploy.php.twig if Deployer feature is disabled

- templates/src/composer.json.twig
Composer 2.6 introduced a new way of handling abandoned packages when running `composer audit`. By now, abandoned packages will be reported only, but the command will not fail in case abandoned packages are required. This changes with Composer 2.7 where it will cause `composer audit` to fail in such cases.
With this PR, the configuration option `audit.abandoned` is explicitly configured as `report` to avoid failures on `composer audit` when using abandoned packages.
> [TASK] Explicitly report abandoned packages with `audit` command

- templates/src/typoscript-lint.yml.twig
This PR enables the `ConfigNoCache` sniff in `typoscript-lint.yml` template.
> [TASK] Enable `ConfigNoCache` sniff in TypoScript linter

- templates/src/typoscript-lint.yml.twig
This PR syncs indentation within TypoScript file in `typoscript-lint.yml`. The indentation level is configured in `.editorconfig` template.
> [TASK] Sync indentation within TypoScript files

- config.yaml
This PR adds PHP 8.3 to the list of selectable PHP versions for new projects.
> [FEATURE] Allow PHP 8.3 as selectable PHP version for new projects

- templates/src/.ddev/config.yaml.twig
This PR updates the `.ddev/config.yaml` template to DDEV v1.22.6. In addition, the used Node version is raised to latest Node 20 LTS.
> [TASK] Update DDEV config template to v1.22.6

- config.yaml
- templates/src/composer.json.twig
This PR dynamically configures the version constraint for `armin/editorconfig-cli` to support `^2.0` as well. This is especially relevant for projects with Symfony v7.
> [TASK] Add support for `armin/editorconfig-cli` ^2.0 in template

- config.yaml
- renovate.json
This PR configures Renovate to update version constraints in the following files:
* `config.yaml` with special package configuration
* `templates/src/composer.json.twig` for each configured dependency
> [TASK] Let Renovate update template version constraints

- templates/src/.gitignore.twig
Using this template inserts a `.gitignore` in the newly created project that prevents from commiting the usually needed `config/*` directory in versions !== v11. Therefore, this PR seeks to allow the VCS coverage by default.
> [BUGFIX] Remove `config/*` references from `.gitignore`

- README.md
- config.yaml
- templates/src/composer.json.twig
This PR drops support for PHP 8.0, since it reached its EOL.
> [!!!][TASK] Drop support for PHP 8.0
